# 로컬 DB 구성
version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: agilehubdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - app-network
    restart: always

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge