spring:
  profiles:
    active: local
    include: oauth, jwt, redis, mail
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0B
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui
  cache:
    disabled: true
  use-fqn: true


aws:
  s3:
    rootURL: https://image.agilehub.store
    bucket: agilehub
    directory: /images
    workingDirectory:
      issue: issue

