spring:
  profiles:
    active: local
    include: oauth, jwt
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0B
      enabled: true

springdoc:
  swagger-ui:
    path: /api/api-docs
  api-docs:
    path: /api/v3/api-docs
  cache:
    disabled: true
  use-fqn: true

aws:
  s3:
    rootURL: https://image.agilehub.store
    bucket: agilehub
    directory: /images
