# test profile
spring:
  config:
    activate:
      on-profile: test
    import:
      - optional:classpath:.env[.properties]

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: true
        default_batch_fetch_size: 100

    open-in-view: false

  sql:
    init:
      mode: never
