spring:
  config:
    activate:
      on-profile: dummy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/agilehubdb?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: never
logging:
  level:
    org.hibernate.SQL: debug
    root: info
    org.hibernate.orm.jdbc.bind: trace