spring:
  profiles:
    active: local
    include: oauth, jwt, redis, mail
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0B
      enabled: true
  server:
    tomcat:
      max-threads: 100
      min-spare-threads: 100

  hikari:
    # 풀 사이즈 설정
    maximum-pool-size: 75
    minimum-idle: 75

    # 시간 관련 설정
    max-lifetime: 50000           # 50초, DB wait_timeout보다 작게
    connection-timeout: 3000      # 3초, 빠른 응답이 필요한 API
    validation-timeout: 1000      # 1초, connection-timeout보다 작게

springdoc:
  swagger-ui:
    path: /swagger-ui
  cache:
    disabled: true
  use-fqn: true


aws:
  credentials:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
  region: ap-northeast-2
  s3:
    rootURL: https://image.agilehub.store
    bucket: agilehub
    directory: /images
    workingDirectory:
      issue: issue


openai:
  api:
    key: ${OPEN_API_KEY}
    url: https://api.openai.com/v1/chat/completions

